/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatWeOfferRouteImport } from './routes/what-we-offer'
import { Route as ValueFrameworkRouteImport } from './routes/value-framework'
import { Route as ValueDefinitionRouteImport } from './routes/value-definition'
import { Route as TransformationRouteImport } from './routes/transformation'
import { Route as TransformaltionRouteImport } from './routes/transformaltion'
import { Route as ToolsetsRouteImport } from './routes/toolsets'
import { Route as ToolsetRouteImport } from './routes/toolset'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ProjectManagementRouteImport } from './routes/project-management'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as ProblemRouteImport } from './routes/problem'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as EchartsRouteImport } from './routes/echarts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BecomePartnerRouteImport } from './routes/become-partner'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsOverviewRouteImport } from './routes/solutions.overview'
import { Route as SolutionsSolutionIdRouteImport } from './routes/solutions.$solutionId'

const WhatWeOfferRoute = WhatWeOfferRouteImport.update({
  id: '/what-we-offer',
  path: '/what-we-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const ValueFrameworkRoute = ValueFrameworkRouteImport.update({
  id: '/value-framework',
  path: '/value-framework',
  getParentRoute: () => rootRouteImport,
} as any)
const ValueDefinitionRoute = ValueDefinitionRouteImport.update({
  id: '/value-definition',
  path: '/value-definition',
  getParentRoute: () => rootRouteImport,
} as any)
const TransformationRoute = TransformationRouteImport.update({
  id: '/transformation',
  path: '/transformation',
  getParentRoute: () => rootRouteImport,
} as any)
const TransformaltionRoute = TransformaltionRouteImport.update({
  id: '/transformaltion',
  path: '/transformaltion',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsetsRoute = ToolsetsRouteImport.update({
  id: '/toolsets',
  path: '/toolsets',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsetRoute = ToolsetRouteImport.update({
  id: '/toolset',
  path: '/toolset',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectManagementRoute = ProjectManagementRouteImport.update({
  id: '/project-management',
  path: '/project-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemRoute = ProblemRouteImport.update({
  id: '/problem',
  path: '/problem',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const EchartsRoute = EchartsRouteImport.update({
  id: '/echarts',
  path: '/echarts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomePartnerRoute = BecomePartnerRouteImport.update({
  id: '/become-partner',
  path: '/become-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsOverviewRoute = SolutionsOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsSolutionIdRoute = SolutionsSolutionIdRouteImport.update({
  id: '/$solutionId',
  path: '/$solutionId',
  getParentRoute: () => SolutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-partner': typeof BecomePartnerRoute
  '/dashboard': typeof DashboardRoute
  '/echarts': typeof EchartsRoute
  '/library': typeof LibraryRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/problem': typeof ProblemRoute
  '/project': typeof ProjectRoute
  '/project-management': typeof ProjectManagementRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/survey': typeof SurveyRoute
  '/toolset': typeof ToolsetRoute
  '/toolsets': typeof ToolsetsRoute
  '/transformaltion': typeof TransformaltionRoute
  '/transformation': typeof TransformationRoute
  '/value-definition': typeof ValueDefinitionRoute
  '/value-framework': typeof ValueFrameworkRoute
  '/what-we-offer': typeof WhatWeOfferRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
  '/solutions/overview': typeof SolutionsOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-partner': typeof BecomePartnerRoute
  '/dashboard': typeof DashboardRoute
  '/echarts': typeof EchartsRoute
  '/library': typeof LibraryRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/problem': typeof ProblemRoute
  '/project': typeof ProjectRoute
  '/project-management': typeof ProjectManagementRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/survey': typeof SurveyRoute
  '/toolset': typeof ToolsetRoute
  '/toolsets': typeof ToolsetsRoute
  '/transformaltion': typeof TransformaltionRoute
  '/transformation': typeof TransformationRoute
  '/value-definition': typeof ValueDefinitionRoute
  '/value-framework': typeof ValueFrameworkRoute
  '/what-we-offer': typeof WhatWeOfferRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
  '/solutions/overview': typeof SolutionsOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-partner': typeof BecomePartnerRoute
  '/dashboard': typeof DashboardRoute
  '/echarts': typeof EchartsRoute
  '/library': typeof LibraryRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/problem': typeof ProblemRoute
  '/project': typeof ProjectRoute
  '/project-management': typeof ProjectManagementRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/survey': typeof SurveyRoute
  '/toolset': typeof ToolsetRoute
  '/toolsets': typeof ToolsetsRoute
  '/transformaltion': typeof TransformaltionRoute
  '/transformation': typeof TransformationRoute
  '/value-definition': typeof ValueDefinitionRoute
  '/value-framework': typeof ValueFrameworkRoute
  '/what-we-offer': typeof WhatWeOfferRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
  '/solutions/overview': typeof SolutionsOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-partner'
    | '/dashboard'
    | '/echarts'
    | '/library'
    | '/portfolio'
    | '/privacy-policy'
    | '/problem'
    | '/project'
    | '/project-management'
    | '/solutions'
    | '/survey'
    | '/toolset'
    | '/toolsets'
    | '/transformaltion'
    | '/transformation'
    | '/value-definition'
    | '/value-framework'
    | '/what-we-offer'
    | '/solutions/$solutionId'
    | '/solutions/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-partner'
    | '/dashboard'
    | '/echarts'
    | '/library'
    | '/portfolio'
    | '/privacy-policy'
    | '/problem'
    | '/project'
    | '/project-management'
    | '/solutions'
    | '/survey'
    | '/toolset'
    | '/toolsets'
    | '/transformaltion'
    | '/transformation'
    | '/value-definition'
    | '/value-framework'
    | '/what-we-offer'
    | '/solutions/$solutionId'
    | '/solutions/overview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-partner'
    | '/dashboard'
    | '/echarts'
    | '/library'
    | '/portfolio'
    | '/privacy-policy'
    | '/problem'
    | '/project'
    | '/project-management'
    | '/solutions'
    | '/survey'
    | '/toolset'
    | '/toolsets'
    | '/transformaltion'
    | '/transformation'
    | '/value-definition'
    | '/value-framework'
    | '/what-we-offer'
    | '/solutions/$solutionId'
    | '/solutions/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BecomePartnerRoute: typeof BecomePartnerRoute
  DashboardRoute: typeof DashboardRoute
  EchartsRoute: typeof EchartsRoute
  LibraryRoute: typeof LibraryRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProblemRoute: typeof ProblemRoute
  ProjectRoute: typeof ProjectRoute
  ProjectManagementRoute: typeof ProjectManagementRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  SurveyRoute: typeof SurveyRoute
  ToolsetRoute: typeof ToolsetRoute
  ToolsetsRoute: typeof ToolsetsRoute
  TransformaltionRoute: typeof TransformaltionRoute
  TransformationRoute: typeof TransformationRoute
  ValueDefinitionRoute: typeof ValueDefinitionRoute
  ValueFrameworkRoute: typeof ValueFrameworkRoute
  WhatWeOfferRoute: typeof WhatWeOfferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-we-offer': {
      id: '/what-we-offer'
      path: '/what-we-offer'
      fullPath: '/what-we-offer'
      preLoaderRoute: typeof WhatWeOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/value-framework': {
      id: '/value-framework'
      path: '/value-framework'
      fullPath: '/value-framework'
      preLoaderRoute: typeof ValueFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/value-definition': {
      id: '/value-definition'
      path: '/value-definition'
      fullPath: '/value-definition'
      preLoaderRoute: typeof ValueDefinitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transformation': {
      id: '/transformation'
      path: '/transformation'
      fullPath: '/transformation'
      preLoaderRoute: typeof TransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transformaltion': {
      id: '/transformaltion'
      path: '/transformaltion'
      fullPath: '/transformaltion'
      preLoaderRoute: typeof TransformaltionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolsets': {
      id: '/toolsets'
      path: '/toolsets'
      fullPath: '/toolsets'
      preLoaderRoute: typeof ToolsetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolset': {
      id: '/toolset'
      path: '/toolset'
      fullPath: '/toolset'
      preLoaderRoute: typeof ToolsetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-management': {
      id: '/project-management'
      path: '/project-management'
      fullPath: '/project-management'
      preLoaderRoute: typeof ProjectManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem': {
      id: '/problem'
      path: '/problem'
      fullPath: '/problem'
      preLoaderRoute: typeof ProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/echarts': {
      id: '/echarts'
      path: '/echarts'
      fullPath: '/echarts'
      preLoaderRoute: typeof EchartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-partner': {
      id: '/become-partner'
      path: '/become-partner'
      fullPath: '/become-partner'
      preLoaderRoute: typeof BecomePartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/overview': {
      id: '/solutions/overview'
      path: '/overview'
      fullPath: '/solutions/overview'
      preLoaderRoute: typeof SolutionsOverviewRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/$solutionId': {
      id: '/solutions/$solutionId'
      path: '/$solutionId'
      fullPath: '/solutions/$solutionId'
      preLoaderRoute: typeof SolutionsSolutionIdRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

interface SolutionsRouteChildren {
  SolutionsSolutionIdRoute: typeof SolutionsSolutionIdRoute
  SolutionsOverviewRoute: typeof SolutionsOverviewRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSolutionIdRoute: SolutionsSolutionIdRoute,
  SolutionsOverviewRoute: SolutionsOverviewRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BecomePartnerRoute: BecomePartnerRoute,
  DashboardRoute: DashboardRoute,
  EchartsRoute: EchartsRoute,
  LibraryRoute: LibraryRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProblemRoute: ProblemRoute,
  ProjectRoute: ProjectRoute,
  ProjectManagementRoute: ProjectManagementRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  SurveyRoute: SurveyRoute,
  ToolsetRoute: ToolsetRoute,
  ToolsetsRoute: ToolsetsRoute,
  TransformaltionRoute: TransformaltionRoute,
  TransformationRoute: TransformationRoute,
  ValueDefinitionRoute: ValueDefinitionRoute,
  ValueFrameworkRoute: ValueFrameworkRoute,
  WhatWeOfferRoute: WhatWeOfferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
