/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatWeOfferRouteImport } from './routes/what-we-offer'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsOverviewRouteImport } from './routes/solutions.overview'
import { Route as SolutionsSolutionIdRouteImport } from './routes/solutions.$solutionId'

const WhatWeOfferRoute = WhatWeOfferRouteImport.update({
  id: '/what-we-offer',
  path: '/what-we-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsOverviewRoute = SolutionsOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsSolutionIdRoute = SolutionsSolutionIdRouteImport.update({
  id: '/$solutionId',
  path: '/$solutionId',
  getParentRoute: () => SolutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/what-we-offer': typeof WhatWeOfferRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
  '/solutions/overview': typeof SolutionsOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/what-we-offer': typeof WhatWeOfferRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
  '/solutions/overview': typeof SolutionsOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/what-we-offer': typeof WhatWeOfferRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
  '/solutions/overview': typeof SolutionsOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/library'
    | '/privacy-policy'
    | '/solutions'
    | '/what-we-offer'
    | '/solutions/$solutionId'
    | '/solutions/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/library'
    | '/privacy-policy'
    | '/solutions'
    | '/what-we-offer'
    | '/solutions/$solutionId'
    | '/solutions/overview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/library'
    | '/privacy-policy'
    | '/solutions'
    | '/what-we-offer'
    | '/solutions/$solutionId'
    | '/solutions/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  LibraryRoute: typeof LibraryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  WhatWeOfferRoute: typeof WhatWeOfferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-we-offer': {
      id: '/what-we-offer'
      path: '/what-we-offer'
      fullPath: '/what-we-offer'
      preLoaderRoute: typeof WhatWeOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/overview': {
      id: '/solutions/overview'
      path: '/overview'
      fullPath: '/solutions/overview'
      preLoaderRoute: typeof SolutionsOverviewRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/$solutionId': {
      id: '/solutions/$solutionId'
      path: '/$solutionId'
      fullPath: '/solutions/$solutionId'
      preLoaderRoute: typeof SolutionsSolutionIdRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

interface SolutionsRouteChildren {
  SolutionsSolutionIdRoute: typeof SolutionsSolutionIdRoute
  SolutionsOverviewRoute: typeof SolutionsOverviewRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSolutionIdRoute: SolutionsSolutionIdRoute,
  SolutionsOverviewRoute: SolutionsOverviewRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  LibraryRoute: LibraryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  WhatWeOfferRoute: WhatWeOfferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
